apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/nodejs/*.log
    output.elasticsearch:
      hosts: ["https://elasticsearch-master:9200"]
      username: elastic
      password: "<ELASTIC_PASSWORD>"
      ssl.enabled: false
