apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pods-and-pvc-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: pods-and-pvc-alerts
      rules:
        - alert: PodCrashLoop
          expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod is restarting frequently"
            description: "Pod has restarted more than 3 times in 5 minutes"

        - alert: PodOOMKilled
          expr: kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod OOMKilled"
            description: "A pod was terminated due to OutOfMemoryKill"

        - alert: DeploymentNotReady
          expr: kube_deployment_status_replicas_available < kube_deployment_spec_replicas
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Deployment replicas mismatch"
            description: "Deployment has fewer available replicas than desired"

        - alert: PVCAlmostFull
          expr: kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes * 100 > 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "PVC usage high"
            description: "PVC usage > 1%"

        - alert: PendingPods
          expr: kube_pod_status_phase{phase="Pending"} > 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pods pending"
            description: "One pod is pending for more than 5 minutes"
