replicas: 2
service:
  type: LoadBalancer
  port: 5601

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "4Gi"

elasticsearchHosts: "https://elasticsearch-master:9200"
persistence:
  enabled: false

extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-es-elastic-user
        key: elastic
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-es-elastic-user
        key: elastic
