replicas: 3
resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "4Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3

logstashPipeline:
  logstash.conf: |
    input { beats { port => 5044 } }
    filter { grok { match => { "message" => "%{COMMONAPACHELOG}" } } }
    output {
      elasticsearch {
        hosts => ["https://elasticsearch-master:9200"]
        user => "${ELASTICSEARCH_USERNAME}"
        password => "${ELASTICSEARCH_PASSWORD}"
        ssl => true
        ssl_certificate_verification => false
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }
