apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: monitoring
type: Opaque
stringData:
  url: "https://hooks.slack.com/services/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"
