apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore
  namespace: monitoring
type: Opaque
stringData:
  thanos.yaml: |
    type: S3
    config:
      bucket: your-prometheus-bucket
      endpoint: s3.amazonaws.com
      access_key: YOUR_AWS_ACCESS_KEY
      secret_key: YOUR_AWS_SECRET_KEY
      insecure: false
